app/urls.py
from django.contrib import admin
from django.urls import path
from .views import FiboView, AckermanView, FactView, HomeView

app_name = 'app'

urlpatterns = [

    path('fibonacci/', FiboView.as_view(), name='fibonacci'),
    path('ackerman/', AckermanView.as_view(), name='ackerman'),
    path('factorial/', FactView.as_view(), name='factorial'),
    path('', HomeView.as_view(), name='home'),


]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
]

app/models.py
from django.db import models

# Create your models here.

app/forms.py
from django import forms 

class FiboForm(forms.Form):
    n = forms.IntegerField(min_value=1, label="")

    def clean(self):
        super().clean()

        n = self.cleaned_data.get('n')

        if n <= 0:
                self._errors['n'] = self.error_class(['Please Enter a positive Integer'])

        return self.cleaned_data    

class AckermanForm(forms.Form):

    m = forms.IntegerField(min_value=1, label="Positive Integer M")
    n = forms.IntegerField(min_value=1, label="Positive Integer N")

    def clean(self):
        super().clean()

        n = self.cleaned_data.get('n')
        m = self.cleaned_data.get('m')

        if n <= 0:
                self._errors['n'] = self.error_class(['Please Enter a positive Integer'])
        
        if m <= 0:
                self._errors['m'] = self.error_class(['Please Enter a positive Integer'])

        return self.cleaned_data    


class FactForm(FiboForm):
    pass

app/views.py
from django.shortcuts import render
from time import perf_counter
from django.views.generic import TemplateView
from .forms import AckermanForm, FactForm, FiboForm 
from django.views import View


class HomeView(TemplateView):
    template_name = "base.html"

class FiboView(View):
    form_class = FiboForm
    template_name = 'fib.html'

    @staticmethod
    def calculate_fib(number):

        if number in [1,2]:
            return 1 
        
        first = 1 
        second = 1 
        for i in range(2,number):
            second += first 
            first = second - first 

        return second


    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            time1 = perf_counter()
            answer = FiboView.calculate_fib(form.cleaned_data['n'])
            time2 = perf_counter()

            return render(request, self.template_name, {'answer': f'{answer}\n calculated in {(time2 - time1)*1000:0.10f} milliseconds', 'form': form})
        else: 
            return render(request, self.template_name, {'form': form})  


class AckermanView(View):
    form_class = AckermanForm
    template_name = 'ack.html'

    @staticmethod
    def calculate_ackerman(m, n):
  
        cache = [[0 for i in range(n + 1)] for j in range(m + 1)]
        for rows in range(m + 1):
            for cols in range(n + 1):
                if rows == 0:       
                    cache[rows][cols] = cols + 1

                elif cols == 0:
                    cache[rows][cols] = cache[rows-1][1]
                else:

                    r = rows - 1
                    c = cache[rows][cols-1]

                    if r == 0:    
                        ans = c + 1
                    elif c <= n:
                        ans = cache[rows-1][cache[rows][cols-1]]
                    else:
                        ans = (c-n)*(r) + cache[r][n]
    
                    cache[rows][cols] = ans
    
        return cache[m][n]


    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            time1 = perf_counter()
            answer = AckermanView.calculate_ackerman(form.cleaned_data['m'], form.cleaned_data['n'])
            time2 = perf_counter()

            return render(request, self.template_name, {'answer': f'{answer}\n calculated in {(time2 - time1)*1000:0.10f} milliseconds', 'form': form})
        else: 
            return render(request, self.template_name, {'form': form})  


class FactView(View):
    form_class = FactForm
    template_name = 'fact.html'

    @staticmethod
    def fact(n):
        out = 1 
        for i in range(1,n+1):
            out *= i

        return out


    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            time1 = perf_counter()
            answer = FactView.fact(form.cleaned_data['n'])
            time2 = perf_counter()

            return render(request, self.template_name, {'answer': f'{answer}\n calculated in {(time2 - time1)*1000:0.10f} milliseconds', 'form': form})
        else: 
            return render(request, self.template_name, {'form': form})  

app/templates/ack.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% if answer %}
<div class="alert alert-primary" role="alert">
    The Answer Is: {{ answer }}
</div>
{% endif %}
<div class="d-flex justify-content-center">


    <form action='{% url 'app:ackerman' %}' method='post'>
        {% csrf_token %}
        <div class="form-group">
            <label>Ackerman Function</label>
            {{ form | crispy }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Interview Test Project</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style>
    .asteriskField {
      color: red;
    }

  </style>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Test App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
<li>        <a class="nav-link" href="{% url 'app:fibonacci' %}" id="navbarDropdownMenuLink"  aria-haspopup="true" aria-expanded="false">
          Fibonacci Sequence
        </a></li>
<li>        <a class="nav-link" href="{% url 'app:ackerman' %}" id="navbarDropdownMenuLink"  aria-haspopup="true" aria-expanded="false">
          Ackerman Function
        </a></li>
<li>                <a class="nav-link" href="{% url 'app:factorial' %}" id="navbarDropdownMenuLink"  aria-haspopup="true" aria-expanded="false">
          Factorial
        </a></li>

      </li>
    </ul>
  </div>
</nav>



{% block content %}

{% endblock content %}



</body>
</html>

app/templates/fact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% if answer %}
<div class="alert alert-primary" role="alert">
    <p class='text-center'>The Answer Is: {{ answer }}</p>
</div>
{% endif %}
<div class="d-flex justify-content-center">


    <form action='{% url 'app:factorial' %}' method='post'>
        {% csrf_token %}
        <div class="form-group">
            <label>Factorial Function</label>
            {{ form|crispy }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

{% endblock content %}

app/templates/fib.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

{% if answer %}
<div class="alert alert-primary" role="alert">
    The Answer Is: {{ answer }}
</div>
{% endif %}

<div class="d-flex justify-content-center">


    <form action='{% url 'app:fibonacci' %}' method='post'>
        <div class="form-group">
            <label>Fibonacci Sequence</label>
            {% csrf_token %}
            {{ form|crispy }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

</div>

{% endblock content %}